main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (Index_view,
                    SubCategoryView,
                    ProductsView,
                    ComparisonView,
)

urlpatterns = [
    path('',Index_view,name='index'),
    path('subcategory/<int:subcategory_id>/',SubCategoryView,name='subcategory'),
    path('products/<int:brand_id>/',ProductsView,name='products'),
    path('comparison/<int:product_id>/',ComparisonView,name='comparison'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pricepoint/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/models.py
from django.db import models

class Category(models.Model):
    '''
    class for major categorys
    '''
    category = models.CharField(max_length=60)
    
    def __str__(self):
        return f'{self.category}'
    
    
class SubCategory(models.Model):
    '''
    Class for subcategory of category
    '''
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    subcategory = models.CharField(max_length=60)
    
    def __str__(self):
        return f'{self.subcategory} of {self.category.category}'
    
    
class Sub_SubCategory(models.Model):
    '''
    Class for subcategory of the sub category
    '''
    subcategory = models.ForeignKey(SubCategory,on_delete=models.CASCADE)
    sub_subcategory = models.CharField(max_length=60)
    
    def __str__(self):
        return f'{self.sub_subcategory} of {self.subcategory.subcategory} of {self.subcategory.category.category}'
    

class OnlineSite(models.Model):
    '''
    Online sites
    '''
    logo = models.ImageField(upload_to='online_store_logos/')
    online_site = models.CharField(max_length=50)
    international = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.online_site } site info'
    
class Brand(models.Model):
    '''
    Brands
    '''
    brand_pic = models.ImageField(upload_to='brandimage/')
    brand_name = models.CharField(max_length=50)
    sub_subcategory = models.ManyToManyField(Sub_SubCategory)
    
    def __str__(self):
        return f'{self.brand_name}'
    
class Product(models.Model):
    '''
    product
    '''
    product_pic = models.ImageField(upload_to='product_picture/',null=True,blank=True)
    product_pic_2 = models.ImageField(upload_to='product_picture/',null=True,blank=True)
    product_pic_3 = models.ImageField(upload_to='product_picture/',null=True,blank=True)
    product_pic_4 = models.ImageField(upload_to='product_picture/',null=True,blank=True)
    sub_subcategory = models.ForeignKey(Sub_SubCategory,on_delete=models.CASCADE,null=True)
    product = models.CharField(max_length=60)
    product_description = models.TextField(null=True)
    product_brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.product} info'
    
class ProductWithPrice(models.Model):
    '''
    Product itself
    '''
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    online_site = models.ForeignKey(OnlineSite,on_delete=models.CASCADE)
    price = models.IntegerField()
    affiliate_link = models.URLField(max_length=1000,null=True,blank=True)
    
    def __str__(self):
        return f'{self.product.product} Price from {self.online_site.online_site}'

main/views.py
from django.shortcuts import render
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
from .models import (Brand,
                     Category,
                     SubCategory,
                     Sub_SubCategory,
                     OnlineSite,
                     Brand,
                     Product,
                     ProductWithPrice,
)

def Index_view(request):
    '''
    This is the function based view for the homepage
    '''
    title = "home"
    categorys = Category.objects.all()
    # subcategorys = SubCategory.objects.all()
    context = {
        "title":title,
        "categorys":categorys,
    }
    
    return render(request,"main/index.html",context)

def SubCategoryView(request, subcategory_id):
    '''
    Sub category
    Arg:
        sub-category
    '''
    title = "sub-category"
    try:
        subcategory = SubCategory.objects.get(id = subcategory_id)
    except ObjectDoesNotExist:
        raise Http404()
    
    context = {
        "subcategory":subcategory
    }
    
    return render(request,"main/subcategory.html",context)

def ProductsView(request,brand_id):
    '''
    brand page
    '''
    title = "brand-page"
    try:
        products = Product.objects.get(product_brand = brand_id)
    except ObjectDoesNotExist:
        products = "Products for this category are still being populated"
        # raise Http404()
    
    
    
    context = {
        "products": products
    }
    
    return render(request,"main/products.html",context)
    
    
def ComparisonView(request,product_id):
    '''
    Comparison page for single product
    '''
    
    title = "comparison"
    
    try:
        comparisonPrices = ProductWithPrice.objects.filter(product = product_id)
    except ObjectDoesNotExist:
        raise Http404()
    
    products = Product.objects.get(id = product_id)
    
    context = {
        "comparisonPrices":comparisonPrices,
        "products":products
    }
    
    return render(request,"main/comparison.html",context)

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link href="https://fonts.googleapis.com/css?family=Spartan&display=swap" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet">
    <!-- My styles -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    <title>Pricepoint</title>
</head>
<body>

    {% include 'main/navbar.html' %}

    {% block content %}

    {% endblock %}

    {% include 'main/footer.html' %}

    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script>
    <!-- Personal scripts -->
    <script type="text/javascript" src="{% static 'scripts/script.js' %}"></script>
</body>
</html>

main/templates/main/comparison.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
<div class="row">
    <div class="col-md-4">
        <img src="{{ products.product_pic.url }}" alt="" class="product-images">
    </div>
    <div class="col-md-4">
        <img src="{{ products.product_pic_2.url }}" alt="" class="product-images">
    </div>
    <div class="col-md-4">
        <img src="{{ products.product_pic_3.url }}" alt="" class="product-images">
    </div>
</div>

<br><br>


    <p>Product Description.</p>
    <small>{{ products.product_description }}</small>
    <hr>
    <p>Best Prices from Stores</p>
<div class="row">
    {% for comparisonPrice in comparisonPrices %}
            <div class = "col-md-4">
            <!-- Card -->
            <div class="card">
    
                <!-- Card image -->
                <div class="view overlay">
                    <img class="card-img-top product-images" src="{{ comparisonPrice.online_site.logo.url }}" alt="Card image cap">
                    <a href="#!">
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>
    
                <!-- Card content -->
                <div class="card-body">
    
                    <!-- Title -->
                    <h4 class="card-title">{{ comparisonPrice.price }}/= Ksh</h4>
    
                    <a href="{{ comparisonPrice.affiliate_link }}" class="btn btn-primary" target="_blank">Shop Here</a>
    
                </div>
    
            </div>
            <!-- Card -->
        </div>
   


    {% endfor %}
</div>
</div>

{% endblock %}

main/templates/main/footer.html
<!-- Footer -->
<footer class="page-footer font-small orange">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://pricepoint.co.ke/"> pricepoint.co.ke</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

main/templates/main/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
        <div class="container logo-top">
            <p class="text-center">
                <img src="{% static 'images/pricepoint.png' %}" alt="logo">
            </p><hr>
            <p class="text-center">Save Time and Money : Get the best deal : Legitimate Brands</p>
            <p class="text-center">Forget the noise focus on products. Simplicity is our motto</p>
        </div>
        <div class="container">
            <img src="{% static 'images/masokologo.jpeg' %}" alt="jumia" class="masoko-landing-page-logo">
            <img src="{% static 'images/jumialogo.png' %}" alt="jumia" class="landing-page-logo">
            <img src="{% static 'images/killimalllogo.png' %}" alt="jumia" class="landing-page-logo">
            <img src="{% static 'images/amazonlogo.png' %}" alt="jumia" class="landing-page-logo">
            <img src="{% static 'images/aliexpresslogo.png' %}" alt="jumia" class="landing-page-logo">
            <hr>
        </div>
        <div class="container">
            <h1 class="text-center">Categorys</h1>
            <div class="row">

                {% for category in categorys %}
                    <div class="col-md-6">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="black white-text">
                                    <tr>
                                        <th scope="col">{{ category.category }}</th>
                                    </tr>
                                </thead>
                                {% if category.subcategory_set.all %}
                                    {% for subcategory in category.subcategory_set.all %}
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="divBox">
                                                        <a href="{% url 'subcategory' subcategory.id %}">
                                                            {{ subcategory.subcategory }}
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    {% endfor %}
                                {% else %}
                                    <tbody>
                                        <tr>
                                            <td>Data to be populated soon ...</td>
                                        </tr>
                                    </tbody> 
                                {% endif %}
                            </table>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        

{% endblock %}

main/templates/main/navbar.html
<!--Main Navigation-->
<header>

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark orange scrolling-navbar">
      <a class="navbar-brand" href="{% url 'index' %}"><strong>Pricepoint</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Policy</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Faq's</a>
          </li>
        </ul>
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link"><i class="fab fa-facebook-f"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link"><i class="fab fa-twitter"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link"><i class="fab fa-instagram"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  
  </header>
  <!--Main Navigation-->

main/templates/main/products.html
{% extends 'main/base.html' %}

{% block content %}

<div class="wrap">
    <div class="container">
       

        <h2 class="text-center">Products from {{ products.product_brand.brand_name }}</h2>

        <div class="row">
        <div class = "col-md-4">
        <!-- Card -->
        <div class="card">

            <!-- Card image -->
            <div class="view overlay">
                <img class="card-img-top product-images" src="{{ products.product_pic.url }}" alt="Card image cap">
                <a href="#!">
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>

            <!-- Card content -->
            <div class="card-body">

                <!-- Title -->
                <h4 class="card-title">{{ products }}</h4>

                <a href="{% url 'comparison' products.id %}" class="btn btn-primary">View Comparisons</a>

            </div>

        </div>
        <!-- Card -->
    </div>
</div>
    </div>
</div>

{% endblock %}

main/templates/main/subcategory.html
{% extends 'main/base.html' %}

{% block content %}
<div class="wrap">
    <div class="container">
        <small>
            <a href="{% url 'index' %}">Home</a> > 
            <a href="{% url 'subcategory' subcategory.id %}">{{ subcategory.subcategory }}</a>
        </small><br><br>
        <h1 class="text-center">{{ subcategory.subcategory }}</h1><br>
        <p class="text-center">*** Please check to see whether what you are looking for is available for comparison ***</p><hr>
    </div>
    <div class="container">
        {% if subcategory.sub_subcategory_set.all %}
            {% for sub_subcategory in subcategory.sub_subcategory_set.all %}
                <button class="collapsible">{{ sub_subcategory.sub_subcategory }}</button>
                <div class="content">
                    {% if sub_subcategory.brand_set.all %}
                        {% for brand in sub_subcategory.brand_set.all %}
                            <a href="{% url 'products' brand.id %}"><p>{{ brand.brand_name }}</p></a>
                        {% endfor %}
                    {% else %}
                        <p>Sorry this sub category does not have brands yet ...</p>
                    {% endif %}
                </div>
            {% endfor %}
        {% else %}
            <p>Populating Soon ...</p>
        {% endif %}
    </div>
</div>
{% endblock %}